SELECT
    id,
    family_id,
    email,
    password_hash,
    display_name,
    role,
    active,
    verification_token,
    verification_token_expires_at,
    provider,
    provider_id,
    reset_password_token,
    reset_password_token_expires_at,
    is_system_admin,
    relationship
FROM
    USERS
WHERE
    verification_token = /* verificationToken */'abc123'
